---
name: Test
on: [push]

jobs:
  lint:
    name: Rubocop
    timeout-minutes: 5
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.5"
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop

  ruby:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.driver }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        redis: ["6.2"]
        ruby: ["3.1", "3.0", "2.7", "2.6", "2.5"]
        driver: ["ruby", "hiredis"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache redis build
        uses: actions/cache@v1
        with:
          path: tmp/cache
          key: "local-tmp-redis-${{ matrix.redis }}-on-${{ matrix.os }}"
      - name: Lower system timeout
        run: sudo sysctl -w net.ipv4.tcp_syn_retries=2
      - name: Test
        run: |
          bundle exec rake ci
        env:
          DRIVER: "${{ matrix.driver }}"
          EXT_PEDANTIC: "1"

  jruby:
    name: JRuby ${{ matrix.ruby }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        redis: ["6.2"]
        ruby: ["jruby-9.3.3.0"]
        driver: ["ruby"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache redis build
        uses: actions/cache@v1
        with:
          path: tmp/cache
          key: "local-tmp-redis-${{ matrix.redis }}-on-${{ matrix.os }}"
      - name: Lower system timeout
        run: sudo sysctl -w net.ipv4.tcp_syn_retries=2
      - name: Test
        run: |
          bundle exec rake ci
        env:
          DRIVER: "${{ matrix.driver }}"
          EXT_PEDANTIC: "1"

  oses:
    name: ${{ matrix.os }} / Ruby ${{ matrix.ruby }} / ${{ matrix.driver }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["macos"] # TODO: "windows" need an adapted script to install redis (e.g. no tar etc)
        redis: ["6.2"]
        ruby: ["2.5"]
        driver: ["ruby", "hiredis"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache redis build
        uses: actions/cache@v1
        with:
          path: tmp/cache
          key: "local-tmp-redis-${{ matrix.redis }}-on-${{ matrix.os }}"
      - name: Test
        run: |
          bundle exec rake ci
        env:
          DRIVER: "${{ matrix.driver }}"
          EXT_PEDANTIC: "1"
